version: "3"

services: 
  reddit-auto-saved-downloader:
    container_name: reddit-auto-saved-downloader
    build:
      context: ./App
    environment: # All are required
      - CLIENT_ID=
      - CLIENT_SECRET=
      - REDDIT_USERNAME=
      - REDDIT_PASSWORD=