version: "3"

services: 
  reddit-auto-saved-downloader:
    container_name: reddit-auto-saved-downloader
    build:
      context: ./App
    environment: 
      - cronjob= #optional defaults to every 2 hours aka "0 0 */2 * * * *" cronjob strings must be 7 long. Set to "@reboot" to run this script immediately and only once. Read the readme for all possible values.
      - limit= #optional defaults to None. None retrieves all your saved reddit posts. Reddit allows for a maximum of 1000 saved posts. Must be a number
    volumes:
      - ./App:/usr/src/app