version: "3"

services: 
  reddit-auto-saved-downloader:
    container_name: reddit-auto-saved-downloader
    build:
      context: ./App
    ports: 
      - 3000:3000
    environment: # All are required
      - CLIENT_ID=
      - CLIENT_SECRET=
      - REDIRECT_URI=